["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
forms = [
    "src/forms.cairo",
]

[profile.devnet.protostar.deploy]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"