[project]
protostar-version = "0.9.0"
lib-path = "lib"

[contracts]
main = ["contracts/main.cairo"]

[build]
cairo-path = ["./lib/cairo_contracts/src"]

[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.project]
network="testnet"
private-key-path = "./.env"
account-address="0x014032DA2716B9903E103E24A0aA4d389d45Bd105547C74d4BE734C46D2bCa09"

[profile.testnet2.project]
gateway-url = "https://alpha4-2.starknet.io"
chain-id = 1536727068981429685321
private-key-path = "./.env"
account-address = "0x063675fa1ecea10063722e61557ed7f49ed2503d6cdd74f4b31e9770b473650c"

[profile.mainnet.project]
network = "mainnet"